/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CheckerRouteImport } from './routes/checker'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FreePlagiarismCheckerForStudentsRouteImport } from './routes/free-plagiarism-checker-for-students'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PlagiarismCheckerForBloggersRouteImport } from './routes/plagiarism-checker-for-bloggers'
import { Route as PlagiarismCheckerForResearchersRouteImport } from './routes/plagiarism-checker-for-researchers'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckerRoute = CheckerRouteImport.update({
  id: '/checker',
  path: '/checker',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FreePlagiarismCheckerForStudentsRoute =
  FreePlagiarismCheckerForStudentsRouteImport.update({
    id: '/free-plagiarism-checker-for-students',
    path: '/free-plagiarism-checker-for-students',
    getParentRoute: () => rootRouteImport,
  } as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PlagiarismCheckerForBloggersRoute =
  PlagiarismCheckerForBloggersRouteImport.update({
    id: '/plagiarism-checker-for-bloggers',
    path: '/plagiarism-checker-for-bloggers',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlagiarismCheckerForResearchersRoute =
  PlagiarismCheckerForResearchersRouteImport.update({
    id: '/plagiarism-checker-for-researchers',
    path: '/plagiarism-checker-for-researchers',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checker': typeof CheckerRoute
  '/contact': typeof ContactRoute
  '/free-plagiarism-checker-for-students': typeof FreePlagiarismCheckerForStudentsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/plagiarism-checker-for-bloggers': typeof PlagiarismCheckerForBloggersRoute
  '/plagiarism-checker-for-researchers': typeof PlagiarismCheckerForResearchersRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checker': typeof CheckerRoute
  '/contact': typeof ContactRoute
  '/free-plagiarism-checker-for-students': typeof FreePlagiarismCheckerForStudentsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/plagiarism-checker-for-bloggers': typeof PlagiarismCheckerForBloggersRoute
  '/plagiarism-checker-for-researchers': typeof PlagiarismCheckerForResearchersRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checker': typeof CheckerRoute
  '/contact': typeof ContactRoute
  '/free-plagiarism-checker-for-students': typeof FreePlagiarismCheckerForStudentsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/plagiarism-checker-for-bloggers': typeof PlagiarismCheckerForBloggersRoute
  '/plagiarism-checker-for-researchers': typeof PlagiarismCheckerForResearchersRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/checker'
    | '/contact'
    | '/free-plagiarism-checker-for-students'
    | '/how-it-works'
    | '/plagiarism-checker-for-bloggers'
    | '/plagiarism-checker-for-researchers'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/checker'
    | '/contact'
    | '/free-plagiarism-checker-for-students'
    | '/how-it-works'
    | '/plagiarism-checker-for-bloggers'
    | '/plagiarism-checker-for-researchers'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/checker'
    | '/contact'
    | '/free-plagiarism-checker-for-students'
    | '/how-it-works'
    | '/plagiarism-checker-for-bloggers'
    | '/plagiarism-checker-for-researchers'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CheckerRoute: typeof CheckerRoute
  ContactRoute: typeof ContactRoute
  FreePlagiarismCheckerForStudentsRoute: typeof FreePlagiarismCheckerForStudentsRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PlagiarismCheckerForBloggersRoute: typeof PlagiarismCheckerForBloggersRoute
  PlagiarismCheckerForResearchersRoute: typeof PlagiarismCheckerForResearchersRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checker': {
      id: '/checker'
      path: '/checker'
      fullPath: '/checker'
      preLoaderRoute: typeof CheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-plagiarism-checker-for-students': {
      id: '/free-plagiarism-checker-for-students'
      path: '/free-plagiarism-checker-for-students'
      fullPath: '/free-plagiarism-checker-for-students'
      preLoaderRoute: typeof FreePlagiarismCheckerForStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plagiarism-checker-for-bloggers': {
      id: '/plagiarism-checker-for-bloggers'
      path: '/plagiarism-checker-for-bloggers'
      fullPath: '/plagiarism-checker-for-bloggers'
      preLoaderRoute: typeof PlagiarismCheckerForBloggersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plagiarism-checker-for-researchers': {
      id: '/plagiarism-checker-for-researchers'
      path: '/plagiarism-checker-for-researchers'
      fullPath: '/plagiarism-checker-for-researchers'
      preLoaderRoute: typeof PlagiarismCheckerForResearchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CheckerRoute: CheckerRoute,
  ContactRoute: ContactRoute,
  FreePlagiarismCheckerForStudentsRoute: FreePlagiarismCheckerForStudentsRoute,
  HowItWorksRoute: HowItWorksRoute,
  PlagiarismCheckerForBloggersRoute: PlagiarismCheckerForBloggersRoute,
  PlagiarismCheckerForResearchersRoute: PlagiarismCheckerForResearchersRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
